---
# connection block
- name: Test playbook to run
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  tasks:
  - name: Create a file with a content
    ansible.builtin.lineinfile:    # module from the internet
     path: /tmp/testfile
     regexp: '^13.59.69.146 foo.lab.net foo' # Search for line that startswith '13'
     line: '3.136.233.237 foo.lab.net foo'
      
