---
# connection block
- name: Test playbook to run
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  tasks:
  - name: Install multiple package on ubuntu
    when: 
      - ansible_facts ['distribution_version'] == "2"
      - ansible_facts ['distribution'] == "Amazon"
    ansible.builtin.package:    # module from the internet
      name: telnet
      state: latest
    ignore_errors: true

   
