---
# connection block
- name: Installing wordpress
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  vars:
    wordpress_version: "4.0.32"
    php_version:       "5.4.16"
  tasks:
  - name: Install multiple package on Amazon
    when: ansible_facts ['distribution'] == "Amazon"
    ansible.builtin.package:    # module from the internet
      name: 
      - httpd
      - php-{{ php_version }}
      - php-mysql-{{ php_version }}
      - telnet
      - wget
      state: present

  - name: Download wordpress
    when: ansible_facts ['distribution'] == "Amazon"
    ansible.builtin.get_url:
      url: http://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
      dest: /tmp/

  - name: Extract wordpress.tgz into /tmp
    when: ansible_facts ['distribution'] == "Amazon"
    ansible.builtin.unarchive:
      src: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      dest: /tmp/
      remote_src: true

  - name: Host Wordpress
    when: ansible_facts ['distribution'] == "Amazon"
    shell: "cp -r /tmp/wordpress/* /var/www/html/"
    ignore_errors: true

  - name: Start web server
    when: ansible_facts ['distribution'] == "Amazon"
    systemd:
      name: httpd
      state: restarted
      enabled: true
      

