---
# connection block
- name: Installing wordpress
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  tasks:
  - name: Install multiple package on Amazon
    when: ansible_facts ['distribution'] == "Amazon"
    ansible.builtin.package:    # module from the internet
      name: 
      - httpd
      - php
      - php-mysql
      - telnet
      - wget
      state: present