---
# connection block
- name: Installing wordpress
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  tasks:
  - name: Install multiple package on Amazon
    when: ansible_facts ['distribution'] == "Amazon"
    ansible.builtin.package:    # module from the internet
      name: 
      - httpd
      - php
      - php-mysql
      - telnet
      - wget
      state: present

  - name: Download wordpress
    ansible.builtin.get_url:
      url: http://wordpress.org/latest.tar.gz
      dest: /tmp/

  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /tmp/wordpress-6.1.1.tar.gz
      dest: /tmp/
      remote_src: true