---
# connection block
- name: Test playbook to run
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  tasks:
  - name: Install multiple package
    ansible.builtin.package:
      name: 
      - telnet
      - elinks
      - lftp
      - unzip
      state: present

  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: johnd
      comment: John Doe
      uid: 1040

  - name: Ensure group exist
    ansible.builtin.group:
      name: "{{ item }}"
      state: present
    with_items:
    - sales
    - billing
    - admins
    - developers
    